### ISSUE TITLE
Flamework: Documentation for flamework.json & tsconfig.json

### ISSUE THREAD

**Issue by jackTabsCode** [Fireboltofdeath/docs.fireboltofdeath.dev#4]
It might be helpful to add a guide that explains the configuration options for flamework.json as well as the transformer options from tsconfig.json. They are briefly mentioned in release notes but not fully explained unless you dive into the code :)

**Comment by Fireboltofdeath** [comment]
https://github.com/Fireboltofdeath/docs.fireboltofdeath.dev/commit/ddea1042405418772502a2f40dc2ce01bb8b29c4
